<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>

<spring:eval var="invoiceConstant" expression="T(com.erp.utils.Constants).INVOICE"/>

<script type="text/javascript" src="${webapp_path}/js/routecard/invoice.js"></script>

<style type="text/css">
	.mandatoryId {
		color: crimson
	}
	.container {
		 margin: 0 auto;
		 padding: 0 30px;
		 width:100%;
	}
	.panel-body {
    	padding-right: 4%;
    	padding-left: 4%;
	}
	.mandatorytoplabel {
		font-style: italic;
		margin: 10px;
		font-size: 12px
	}
	.panel-heading>a>.glyphicon{ 
		color:#fff;
	}
	.panel-heading{
		font-size:16px;
	    font-weight: bold;
	    font-style:normal
	}
	.text-left{
		text-align:left;
	}
	strong { 
		padding: 0 5px 0 15px;
	}
	.pdtop { 
		padding: 5px 0px; 
	}
	.submit-btn.disabled {
  		opacity: 0.65; 
  		cursor: not-allowed;
	}
	.select2 {
		width:100% ! important;
	}
	.select2-selection {
		height: 32px ! important; 
		padding-left: 6px;
	}
	.gi-2x{font-size: 2em;}
	.gi-3x{font-size: 3em;}
	.gi-4x{font-size: 4em;}
	.gi-5x{font-size: 5em;}
</style>

<div class="container">
	<div class="panel panel-primary">
		<div class="panel-heading">
			  ${formTitle} (<c:out value="${routeCardNo}"></c:out>)
			  <a href="${webapp_path}/listRouteCard.sp" class="pull-right tooltipLink" data-toggle="tooltip" title="List Route Card">
			  <span class="glyphicon  glyphicon-th-list pull-right"></span>
			  </a>
	    </div>
		<div class="mandatoryId mandatorytoplabel">*&nbsp;Mandatory fields</div>
		<div class="panel-body">
        	<!-- Form section - start -->
        	<form:form id="invoiceForm" class="form-horizontal">
			    
			    <!-- Hidden Elements -->
			    <form:hidden path="id" id="invoiceId"/>
			    <form:hidden path="routeCardNo" id="routeCardNo"/>
			    <input type="hidden" id="hiddenQuantity"/>
			    
			    <a href="javascript:void(0)" onclick="loadBarcodeImg()"  class="pull-right tooltipLink"  title="Print Invoice Barcode"><span style="color:#333;" class="glyphicon glyphicon-barcode gi-3x"></span></a>
			  
			    <div class="form-group">
			    	<div class="col-xs-2">
						<label class="control-label"><span class="mandatoryId">*</span>Invoice Date</label>
					</div>
					<div class="col-xs-4">
						<div id="invoiceDate" class="input-group date form_date" data-date-format="dd-MM-yyyy" data-link-field="invoiceDteHidId"  data-link-format="yyyy-mm-dd">
							<input id="invoiceDateTxtbx" type="text" class="form-control" name="invoiceDateValidation" readonly/>
							<div class="input-group-addon">
								<span class="glyphicon glyphicon-calendar"></span>
							</div>
						</div>
					</div>
					<form:hidden id="invoiceDteHidId" path="invoiceDate"/>
					<div class="col-xs-2">
			        	<input class="submit-btn hidden" id="addNewInvoice" name="commit" value="Add New Invoice" type="button"/>
			    	</div>
			    </div>
			    
		    	<div class="form-group">
			    	<div class="col-xs-2">
						<label class="control-label"><span class="mandatoryId">*</span>Invoice Number</label>
					</div>
			    	<div class="col-xs-4">
			            <form:input class="form-control" path="invoiceNumber" id="invoiceNumber"/>
			        </div>
			    </div>
				 
				<div class="form-group">
			    	<div class="col-xs-2">
						<label class="control-label"><span class="mandatoryId">*</span>Generated by</label>
					</div>
			    	<div class="col-xs-4">
			            <form:select path="generatedBy" class="form-control" id="generatedBy">
					  		<form:option value="" selected="selected">Select</form:option>
					  		<form:options items="${usersList}" itemLabel="fullNameWithUserName" itemValue="id"/>
				        </form:select>
			        </div>
			    </div>
			    
			    <div class="form-group">
			    	<div class="col-xs-2">
						<label class="control-label"><span class="mandatoryId">*</span>Quantity</label>
					</div>
			    	<div class="col-xs-4">
			            <form:input class="form-control" path="quantity" id="quantity"/>
			        </div>
			        <div class="col-xs-4 hidden" id="remainingQuantity">
			        	<label class="control-label"></label>
			            <input type="hidden" name="remainingQuantity" id="hiddenRemTotQuan"/>
			        </div>
			    </div>
			    
				<div class="form-group">
					<div class="col-xs-1">
			            <input class="submit-btn" id="inv-submit" name="commit" value="Submit" type="submit"/>
			            <input class="submit-btn hidden" id="inv-update" name="commit" value="Update" type="submit">
		            </div>
		            <div class="col-xs-1">
		            	<input type="reset" class="submit-btn" id="inv-reset" name="commit" value="Reset" onclick="resetForm(this.form)"/>
			            <input class="submit-btn hidden" id="inv-delete" name="commit" value="Delete" type="submit"/>
		            </div>
		    	</div>
		    	
			</form:form>
			<!-- Form section - End -->
			
			<!-- Existing table Section - Start -->
			<c:choose>
				<c:when test="${not empty invoiceDetails && fn:length(invoiceDetails)>0}">
					<div class="table-responsive">
						<table class="table table-hover table-bordered">
							<thead>
								<tr><th colspan="12">Invoice Details</th></tr>
								<tr>
								<c:forEach begin="1" end="2">
									<th>Date</th>
									<th colspan="1">Invoice Number</th>
									<th>Generated By</th>
									<th>Qty (Nos)</th>
									<th>Action</th>
								</c:forEach>
								</tr>
							</thead>
							<tbody>
								<tr class="tblRow">
									<c:forEach var="obj" items="${invoiceDetails}" varStatus="loop">
						        	    <td class="indDateFormat">${obj.invoiceDate}</td>
										<td>${obj.invoiceNumber}</td>
										<td title="${obj.fullNameWithUserName}">${obj.firstName}</td>
										<td>${obj.quantity}</td>
										<c:if test="${obj.invoiceNumber ne null}">
											<td><a href="javascript:void(0)" onclick="update(${obj.id})" title="Update Invoice"><b>Edit</b></a></td>
										</c:if>
										<c:set var="i" value="${loop.index}"></c:set>
										<c:if test="${(i mod 2) != 0}">
											</tr><tr class="tblRow">
										</c:if>
									</c:forEach>
							    </tr>
							</tbody>
						</table>
					</div>
				</c:when>
				<c:otherwise>
					<div class="alert alert-info" style="text-align:center;font-weight:bold;font-size:24px">No Invoice Yet &#9785;</div>
			    </c:otherwise>
			</c:choose>
			<!-- Exisitng table Section - End -->
			
			<div class="hidden" id="invoiceJson">
				<c:out value="${invoiceJson}"></c:out>
			</div>
			
        </div>
   	</div>
</div>

<!--      Barcode Image popup starts      -->
   <div class="modal fade" id="modalBarcodeImgID" tabindex="-1" role="dialog" aria-labelledby="modalGrnID">
     <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                 <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                 <h3 class="modal-title" style="color:#dc446e" ><span>Generated Barcode</span></h3>
                 <h4 class="modal-title" id="modalGrnNoID">Route Card NO :</h4>
            </div>
            <div class="modal-body">
	       		 <div class="form-group">
	       		 	<img id="barcodeImgID" src=""/>
	       		 </div>
	       		 <div class="form-group">
                   <label>No of Copies</label>
                   <input type="text" class="form-control" style="width:100px" name="noOfCopies" id="noOfCopies">
                 </div>
      	    </div>
		    <div class="modal-footer">
		  	    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		        <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="printBarcode()">Print</button>
		    </div>
    	</div>
 	 </div>
	</div>
<!--      Barcode Image popup ends      -->

<script type="text/javascript">
function printBarcode(){
	var id=$("#invoiceNumber").val();
	var noOfCopies = $("#noOfCopies").val();
	var url="${webapp_path}/printbarcode.sp";
	$.get(url,{grnNo:id,noOfCopies:noOfCopies},function(data,status){});
}
</script>

<c:if test="${from == invoiceConstant && not empty invoiceId}"> 
	<input type="hidden" name="invoiceId" id="invoiceIdFromList" value="${invoiceId}"/>
	<script type="text/javascript">
		$(document).ready(function() {
			var invoiceId = $("#invoiceIdFromList").val();
			update(invoiceId);
		});
	</script>
</c:if>
